# print("hello world")
# print()
# print(len("hello world"))
mystring="hello world"
# print(mystring[0])
# print(mystring[1])
# print(mystring[2])
# print(mystring[-1])
# print(mystring[-3])
# print(mystring[:7])
# print(mystring[:])
print(mystring[1:3])
# print(mystring[::2])
# print(mystring[1:7:2])
# print(mystring[::-1])
